name: GitHub Actions
on:
  push:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: react test
        run: npm test
      - name: lint code
        run: npm run lint
      - name: lint code fix
        run: npm run lint -- --fix
      - name: build project
        run: npm run build
